sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tauseefnawaz/docker-react-project -f Dockerfile.dev .

script:
  - docker run -e CI=true tauseefnawaz/docker-react-project npm run test -- --coverage